# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-12-07 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0004_auto_20190506_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='classes',
            field=models.ManyToManyField(blank=True, related_name='classes', to='mall.Classify', verbose_name='分类'),
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='mall.Tag', verbose_name='标签'),
        ),
    ]
